## Complete Numpy Documentation

# 1. ARRY CREATION FUNCTION

In [27]:
import numpy as np

In [323]:
#creat an arry from a list
a=np.array([1,2,3,4])
print("Array:",a)

Array: [1 2 3 4]


In [326]:
print("Array a:",a)

Array a: [1 2 3 4]


In [328]:
#creat an array with evenly spaced values
b = np.arange(0,10,2) # values from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 2 4 6 8]


In [330]:
b1 = np.arange(0,10,3)
print("Array:",b1)

Array: [0 3 6 9]


In [68]:
#creat an array with linear spaced values
c = np.linspace(0,1,5) # 5 values evenly spaced between 0 & 1
print("Array:",c)

Array: [0.   0.25 0.5  0.75 1.  ]


In [70]:
c1 = np.linspace(0,1,10)#np.linspace is also include endpoint,that how it's designed.
print("Array:",c1)

Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [80]:
#creat an array filled with zeros
d = np.zeros((2,3))
print("Array:",d)


Array: [[0. 0. 0.]
 [0. 0. 0.]]


In [82]:
np.zeros((2,3),dtype=int)#converted float to int


array([[0, 0, 0],
       [0, 0, 0]])

In [84]:
#creat an array filled with ones
e = np.ones((3,2)) #3*2 array of ones

In [86]:
print("Array:",e)

Array: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [94]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [98]:
#creat an identity matrix
f = np.eye(4) # 4*4 identity matrix
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [102]:
f1 = np.eye(5)#it creates a 5x5 identity matrix
print("identity matrix f1:\n",f1)#The \n in your "print statement" adds a newline 
                                #before the matrix for cleaner formatting.

identity matrix f1:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 2.Array Manipulation Functions

In [152]:
#Reshape an array without changing its data
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) #reshape to 1*3
print("Reshaped Array:",reshaped)

Reshaped Array: [[1 2 3]]


In [160]:
a2 = np.array([3,5,6,6])
reshape = np.reshape(a2,(4,1))#reshape to 4*1
print("Reshape Array:\n",reshape)

Reshape Array:
 [[3]
 [5]
 [6]
 [6]]


In [123]:
#Flatten an array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)# Flatten to 1D array
print("Flattened Array:",flattened)

Flattened Array: [1 2 3 4]


In [168]:
f2=np.array([[2,3],[4,5]])
flattened = np.ravel(f2)
print("Flattened Array:",flattened)

Flattened Array: [2 3 4 5]


In [125]:
type(f1)

numpy.ndarray

In [127]:
type(flattened)

numpy.ndarray

In [137]:
#Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) #Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [172]:
e2=np.array([[4,5],[6,7]])#np.transpose() flips the array over its diagonal — 
transposed=np.transpose(e2)#it turns rows into columns and columns into rows.
print("Transposed Array:\n",transposed)

Transposed Array:
 [[4 6]
 [5 7]]


In [174]:
#stack arrays vertically
a2 = np.array ([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) #stack a and b vertically
print("stacked arrays:\n",stacked)

stacked arrays:
 [[1 2]
 [3 4]]


In [178]:
#stack arrays horizontaly
h1=np.array([1,2])
h2=np.array([3,4])
stacked = np.hstack([h1,h2])#stack h1 and h2 horizontaly
print("Stacked Arrays:\n",stacked)

Stacked Arrays:
 [1 2 3 4]


# 3.Mathematical Functions

In [144]:
# add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2) #Add 2 to each element
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [182]:
a=np.array([2,4,6,8])
added=np.add(a,2) #add 2 to each element
print("Added 2 to h:",added)

Added 2 to h: [ 4  6  8 10]


In [188]:
a

array([2, 4, 6, 8])

In [190]:
g

array([1, 2, 3, 4])

In [186]:
#square each element
squared = np.power(g,2) # square each element)
print("Square g:",squared)

Square g: [ 1  4  9 16]


In [194]:
#Don't product of two arrays
a=np.array([1,2,3])
dot_product = np.dot(a,g) #dot product of a and g
print("Dot product of a and g:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [196]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [204]:
a3=np.array([1,2,3])#for 1D array
dot_product = np.dot(a1,a)
print("Dot_product of a1 and a:",dot_product)


Dot_product of a1 and a: 14


In [332]:
a2=([1,2,3])
a4=np.array([1,2,3])
dot_product = np.dot(a1,a2)
print("Dot_product of a1 and a:",dot_product)



Dot_product of a1 and a: 14


In [210]:
a4=([1],[2],[3])
print(a4)
print(a1)

([1], [2], [3])
[1 2 3]


In [212]:
Dot_Product = a1@a2#For 2D array
print(Dot_Product)

14


In [214]:
dot_product=np.dot(a1,a4)#For 2D array
print(dot_product)

[14]


In [216]:
dot_product=np.matmul(a1,a4)#For 2D array
print(dot_product)

[14]


# 4. Statistical Function

In [240]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [224]:
#Standard deviation of an array
std_dev = np.std(s)
print("standard deviation of s:",std_dev)


standard deviation of s: 1.118033988749895


In [232]:
#Minimuum element of an array
minimum=np.min(s)
print("min of s:",minimum)

min of s: 1


In [234]:
#Maximum element of an array
maximum = np.max(s)
print("Max of s:",minimum)

Max of s: 1


# 5. Linear Algebra Functions

In [242]:
#Create a matrix
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [246]:
#Determinant of a mtrix
determinant = np.linalg.det(matrix)#(1*4)-(2*3)
print("Determinant of matrix:",determinant)

Determinant of matrix: -2.0000000000000004


In [254]:
#Inverse of a matrix
inverse = np.linalg.inv(matrix)#1/determination
print("Inverse of matrix:\n",inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random Sampling Function

In [263]:
#Generate random values between 0 nd 1
random_values= np.random.rand(3) # array of 3 random values between 0 & 1
print("Random Values:",random_values)

Random Values: [0.45677184 0.8128408  0.83995782]


In [267]:
#Set seed for reproductivity
np.random.seed(0)

#Generate random values between 0 and 1
random_values= np.random.rand(3)## array of 3 random values between 0 & 1 but not 1
print("Random Values:",random_values)

Random Values: [0.5488135  0.71518937 0.60276338]


In [357]:
#Generate random integers
rand_ints = np.random.randint(0,10,size=10) #Random integers between 0 & 10
print("Random integers:",rand_ints)

Random integers: [3 3 7 0 1 9 9 0 4 7]


In [361]:
#Set seed for productivity
np.random.seed(0)#every time you run it, you’ll get the same output:
rand_ints = np.random.randint(0,10,size=7)#random integers will not work,output will be same
print("Random Integers:",rand_ints)

Random Integers: [5 0 3 3 7 9 3]


# 7. Boolean & Logical Fuctions

In [288]:
#Check if all elementts are True
#all
logical_test = np.array([True,False,True])
all_true = np.all(logical_test) # allfalue must true for output True
print("All Element True:",all_true)

All Element True: False


In [290]:
#Check if all elements are True
logical_test = np.array([False,False,False])
all_true = np.all(logical_test) #chcek if all are True
print("All lement True:",all_true)

All lement True: False


In [294]:
#check if all the element are True
#any

any_true = np.any(logical_test)
print("Any Elements True:",any_true)#if any element is True than it provide output True


Any Elements True: False


# 8. Set Operations

In [303]:
#Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [305]:
#union of two arrays
union = np.union1d(set_a,set_b)
print("union of a and b:",union)

union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Fuctions

In [349]:
#Array attributes
a = np.array([1,2,3])
shape = a.shape # shape  of the array
size = a.size # number of elements
dimensions = a.ndim #number of dimensions
dtype = a.dtype # Data type of the array

print("shape of a:",shape)
print("Size of :",size)
print("Number of  dimensions of a:",dimensions)
print("Data type of a:",dtype)

shape of a: (3,)
Size of : 3
Number of  dimensions of a: 1
Data type of a: int32


# 10. Other Functions

In [311]:
#Create a copy an array
a=np.array([1,2,3])
copied_array = np.copy(a) #create a copy of array 
print("Copied of array:",copied_array)


Copied of array: [1 2 3]


In [373]:
q1=np.array([4,5,6])#q1 and copied_array have the same values.
                          #But they are stored in different memory locations 
copied_array=np.copy(q1)
print("Copied of array:",copied_array)

Copied of array: [4 5 6]


In [377]:
a

array([1, 2, 3])

In [375]:
#Size in bytes of an array
array_size_in_bytes = a.nbytes #each integer (int32) occupies 4 bytes, and there are 3 elemt
#so the total is 3 * 4 = 12 bytes.
print("Size of a in bytes:",array_size_in_bytes)

Size of a in bytes: 12


In [319]:
#check if two arrays share memory
shared = np.shares_memory(a,copied_array) 
print("dO a and copied_array share memory?",shared)


dO a and copied_array share memory? False
